#test0.py

test = [1,2,3]
test[3]


Traceback (most recent call last):
  File "D:\pleiades\workspace\rinkou\src\test.py", line 4, in <module>
    test[3]
IndexError: list index out of range
